package com.dearmoon.shield.modea;

import android.content.Context;
import android.util.Log;

import com.dearmoon.shield.data.FileSystemEvent;
import com.dearmoon.shield.detection.UnifiedDetectionEngine;

/**
 * ModeAFileCollector — converts raw kernel telemetry events (received as
 * {@link ShieldEventData} structs from the root daemon) into the same
 * {@link FileSystemEvent} type that Mode-B's FileSystemCollector produces,
 * then forwards them directly to {@link UnifiedDetectionEngine}.
 *
 * This is the critical integration point between Mode-A and the existing
 * detection pipeline. No detection logic lives here — this class is purely
 * a translation / bridging layer.
 *
 * Operation mapping
 * -----------------
 *   eBPF "BURST" / "WRITE"  → FileSystemEvent operation "MODIFY"
 *   eBPF "READ"             → FileSystemEvent operation "READ"
 *   eBPF "FSYNC"            → FileSystemEvent operation "FSYNC"
 *   eBPF "EXEC"             → FileSystemEvent operation "EXEC"
 *
 * The UnifiedDetectionEngine acts on "MODIFY" events for entropy analysis.
 * All other types are stored for BehaviorCorrelationEngine's 5-second window.
 */
public class ModeAFileCollector {

    private static final String TAG = "SHIELD_MODE_A";

    private final UnifiedDetectionEngine              detectionEngine;
    private final com.dearmoon.shield.data.EventMerger eventMerger;
    private final com.dearmoon.shield.data.TelemetryStorage storage;
    private final int myUid;
    private final String appDataDir;

    /**
     * @param detectionEngine Shared engine from {@link com.dearmoon.shield.ShieldApplication}.
     * @param eventMerger     Shared EventMerger from {@link com.dearmoon.shield.ShieldApplication}
     *                        so Mode A and Mode B events about the same file can be deduplicated
     *                        into a single database row.
     */
    public ModeAFileCollector(UnifiedDetectionEngine detectionEngine,
                              com.dearmoon.shield.data.EventMerger eventMerger) {
        this.detectionEngine = detectionEngine;
        this.eventMerger     = eventMerger;
        context = detectionEngine != null ? detectionEngine.getContext() : null;
        this.storage = new com.dearmoon.shield.data.TelemetryStorage(context);
        
        int uid = -1;
        String dataDir = "";
        if (context != null) {
            uid = context.getApplicationInfo().uid;
            java.io.File d = android.os.Environment.getDataDirectory();
            dataDir = (d != null ? d.getAbsolutePath() : "") + "/data/com.dearmoon.shield";
        }
        this.myUid = uid;
        this.appDataDir = dataDir;
    }

    private final android.content.Context context;

    /**
     * Convert a single kernel telemetry event and inject it into the
     * detection pipeline.
     *
     * @param data  raw event received from the root daemon
     */
    public void onKernelEvent(ShieldEventData data) {
        if (data == null) {
            return;
        }

        // SELF-EXCLUSION: Ignore all events generated by SHIELD's own UID or data directory.
        // This prevents infinite loops and hides shield_events.db from the telemetry log.
        if (data.uid == myUid) {
            return;
        }
        if (data.filename != null && data.filename.startsWith(appDataDir)) {
            return;
        }

        // Filename may be empty when the process exited before the 500ms daemon poll.
        // We still forward the event so SPRT and behavior scoring can act on the
        // write-rate signal even without a resolvable file path.
        String filename  = (data.filename != null && !data.filename.isEmpty())
                ? data.filename : "";
        String operation = mapOperation(data.operation);
        long sizeApprox  = Math.max(0L, data.bytes);

        Log.i(TAG, String.format(
                "%s pid=%d uid=%d file=%s bytes=%d",
                data.operation, data.pid, data.uid,
                filename.isEmpty() ? "<unknown>" : filename, data.bytes));

        FileSystemEvent event = new FileSystemEvent(
            filename,
            operation,
            sizeApprox,   // sizeBefore
            sizeApprox    // sizeAfter
        );
        event.setUid(data.uid);
        event.setMode("MODE_A");  // proper setter — no reflection needed

        // Merge with any recent Mode B event, or add as new
        com.dearmoon.shield.data.EventMerger.MergedEvent merged = eventMerger.mergeEvent(event, "MODE_A");
        // Store as HybridFileSystemEvent for DB (source/merge info)
        com.dearmoon.shield.data.HybridFileSystemEvent hybrid = new com.dearmoon.shield.data.HybridFileSystemEvent(event, merged.source, merged.mergeFlag);
        storage.store(hybrid);
        // Forward to detection engine (for now, use the FileSystemEvent part)
        detectionEngine.processFileEvent(event);
    }

    private static String mapOperation(String bpfOp) {
        if (bpfOp == null) return "UNKNOWN";
        switch (bpfOp) {
            case "WRITE":
            case "BURST": return "MODIFY";
            case "READ":   return "READ";
            case "FSYNC":  return "FSYNC";
            case "EXEC":   return "EXEC";
            default:       return bpfOp;
        }
    }
}
